# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
defaults: &defaults
    adapter: postgresql
    encoding: utf8
    pool: 10
    host: localhost
    port: 5432

development:
    <<: *defaults
    database: inv_dev
    username: postgres
    password: postgres